window.movies = [
    {
        id: "aftersun",
        title: "Aftersun",
        year: "(2022)",  
        director: "Charlotte Wells",
        trailer: "https://youtu.be/vXKcWRu8K_U",
        rated: 5,
        tagline: "Memory burns.",
        description: "Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between miniDV footage as she tries to reconcile the father she knew with the man she didn't.",
        poster: "./posters/aftersun (2022)/jeXmhP2zbUkREMRqFOYIwQOk49T.jpg",
    },
    {
        id: "everything-everywhere-all-at-once",
        title: "Everything Everywhere All At Once",
        year: "(2022)",
        director: "Daniel Kwan, Daniel Scheinert",
        trailer: "https://youtu.be/wxN1T1uxQ2g",
        rated: 5,
        tagline: "The universe is so much bigger than you realize.",
        description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
        poster: "./posters/everything everywhere all at once (2022)/q2VDgaPHJVZ6YXyXdycVM2F2d7E.jpg",
    },
    {
        id: "heat",
        title: "Heat",
        year: "(1995)",
        director: "Michael Mann",
        trailer: "https://youtu.be/14oNcFxiVaQ",
        rated: 5,
        tagline: "A Los Angeles crime saga.",
        description: "Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
        poster: "./posters/heat (1995)/twXYxcrup1QzyT84g2kbuz1iN01.jpg",
    },
    {
        id: "minari",
        title: "Minari",
        year: "(2020)",
        director: "Lee Isaac Chung",
        trailer: "https://youtu.be/KQ0gFidlro8",
        rated: 5,
        description: "A Korean American family moves to an Arkansas farm in search of its own American dream. Amidst the challenges of this new life in the strange and rugged Ozarks, they discover the undeniable resilience of family and what really makes a home.",
        poster: "./posters/minari (2021)/6mPNdmjdbVKPITv3LLCmQoKs9Zw.jpg",
    },
    {
        id: "chungking-express",
        title: "Chungking Express",
        year: "(1994)",
        director: "Wong Kar-wai",
        trailer: "https://youtu.be/C3NDz_7KP2g",
        rated: 5,
        tagline: "What a difference a day makes.",
        description: "Two melancholic Hong Kong policemen fall in love: one with a mysterious underworld figure, the other with a beautiful and ethereal server at a late-night restaurant.",
        poster: "./posters/chungking express (1994)/43I9DcNoCzpyzK8JCkJYpHqHqGG.jpg",
    },
    {
        id: "nope",
        title: "Nope",
        year: "(2022)",
        director: "Jordan Peele",
        trailer: "https://youtu.be/In8fuzj3gck",
        rated: 5,
        tagline: "What’s a bad miracle?",
        description: "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
        poster: "./posters/nope (2022)/krvPgQ44o33hEpZfXnPTDoZz62S.jpg",
    },
    {
        id: "house-of-hummingbird",
        title: "House of Hummingbird",
        year: "(2019)",
        director: "Kim Bora",
        trailer: "https://youtu.be/P1OwDXmdedQ",
        rated: 5,
        tagline: "Among all the people you know, how many really understand what's going on inside you?",
        description: "Whatever she does, Eunhee feels like an outsider. Then her new Chinese teacher turns out to be so utterly different from everybody else. A compassionate and meticulously told narrative of a seemingly regular summer that leaves nothing unchanged.",
        poster: "./posters/house of hummingbird (2019)/azqkMjfwdXuK6OzrrGNYyUnHOAQ.jpg",
    },
    {
        id: "in-the-mood-for-love",
        title: "In the Mood for Love",
        year: "(2000)",
        director: "Wong Kar-wai",
        trailer: "https://youtu.be/m8GuedsQnWQ",
        rated: 5,
        tagline: "Feel the heat, keep the feeling burning, let the sensation explode.",
        description: "Taking place in Hong Kong of 1962, a melancholy story about the love between a woman and a man who live in the same building and one day find out that their husband and wife had an affair with each other.",
        poster: "./posters/in the mood for love (2000)/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg",
    },
    {
        id: "spirited-away",
        title: "Spirited Away",
        year: "(2001)",
        director: "Hayao Miyazaki",
        trailer: "https://youtu.be/ByXuk9QqQkk",
        rated: 5,
        description: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        poster: "./posters/spirited away (2001)/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    },
    {
        id: "all-about-lily-chou-chou",
        title: "All About Lily Chou-Chou",
        year: "(2001)",
        director: "Shunji Iwai",
        trailer: "https://youtu.be/Kwlh-z2R8QE",
        rated: 5,
        tagline: "Pain can take you in prison. The ether can set you free.",
        description: "Charts the troubled teenage years of students Yūichi Hasumi and Shūsuke Hoshino, exploring the shifting and complex power dynamics of their relationship against the backdrop of Yūichi's love for the dreamy and abstract music of fictional pop star Lily Chou-Chou.",
        poster: "./posters/all about lily chou-chou (2001)/cgYcTxXDAYJg8Wc6a15xe2SUZPH.jpg",
    },
    {
        id: "the-shawshank-redemption",
        title: "The Shawshank Redemption",
        year: "(1994)",
        director: "Frank Darabont",
        trailer: "https://youtu.be/PLl99DlL6b4",
        rated: 4,
        tagline: "Fear can hold you prisoner. Hope can set you free.",
        description: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        poster: "./posters/the shawshank redemption (1994)/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
    },
    {
        id: "pearl",
        title: "Pearl",
        year: "(2022)",
        director: "Ti West",
        trailer: "https://youtu.be/L5PW5r3pEOg",
        rated: 4,
        tagline: "The X-traordinary origin story.",
        description: "Trapped on her family’s isolated farm, Pearl must tend to her ailing father under the bitter and overbearing watch of her devout mother. Lusting for a glamorous life like she’s seen in the movies, Pearl’s ambitions, temptations, and repressions collide.",
        poster: "./posters/pearl (2022)/z3NsdQn6rEWxY8JI9stsuwkAyk2.jpg",
    },
    {
        id: "bones-and-all",
        title: "Bones and All",
        year: "(2022)",
        director: "Luca Guadagnino",
        trailer: "https://youtu.be/pjMt1MIk2EA",
        rated: 4,
        description: "Abandoned by her father, a young woman embarks on a thousand-mile odyssey through the backroads of America where she meets a disenfranchised drifter. But despite their best efforts, all roads lead back to their terrifying pasts and to a final stand that will determine whether their love can survive their otherness.",
        poster: "./posters/bones and all (2022)/oVQYItnGtRWkbCpQRD4ISXTZPP8.jpg",
    },
    {
        id: "tar",
        title: "TÁR",
        year: "(2022)",
        director: "Todd Field",
        trailer: "https://youtu.be/Na6gA1RehsU",
        rated: 3,
        description: "The film, set in the international world of classical music, centers on Lydia Tár, widely considered one of the greatest living composer/conductors and first-ever female chief conductor of a major German orchestra.",
        poster: "./posters/tar (2022)/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
    },
    {
        id: "fight-club",
        title: "Fight Club",
        year: "(1999)",
        director: "David Fincher",
        trailer: "https://youtu.be/qtRKdVHc-cE",
        rated: 5,
        tagline: "Mischief. Mayhem. Soap.",
        description: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
        poster: "./posters/fight club (1999)/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    },
    {
        id: "drive",
        title: "Drive",
        year: "(2011)",
        director: "Nicolas Winding Refn",
        trailer: "https://youtu.be/KBiOF3y1W0Y",
        rated: 5,
        tagline: "There are no clean getaways.",
        description: "Driver is a skilled Hollywood stuntman who moonlights as a getaway driver for criminals. Though he projects an icy exterior, lately he's been warming up to a pretty neighbor named Irene and her young son, Benicio. When Irene's husband gets out of jail, he enlists Driver's help in a million-dollar heist. The job goes horribly wrong, and Driver must risk his life to protect Irene and Benicio from the vengeful masterminds behind the robbery.",
        poster: "./posters/drive (2011)/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    },
    {
        id: "her",
        title: "Her",
        year: "(2013)",
        director: "Spike Jonze",
        trailer: "https://youtu.be/XsQqMwacZQw",
        rated: 3,
        tagline: "A Spike Jonze Love Story",
        description: "In the not so distant future, Theodore, a lonely writer, purchases a newly developed operating system designed to meet the user's every need. To Theodore's surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
        poster: "./posters/her (2013)/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    },
    {
        id: "doctor-strange-in-the-multiverse-of-madness",
        title: "Doctor Strange in the Multiverse of Madness",
        year: "(2022)",
        director: "Sam Raimi",
        trailer: "https://youtu.be/aWzlQ2N6qqg",
        rated: 2,
        tagline: "Enter a new dimension of Strange.",
        description: "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
        poster: "./posters/doctor strange in the multiverse of madness (2022)/fwBl3J2aEXru6mrr9Xg8O99Iz2K.jpg",
    },
    {
        id: "little-miss-sunshine",
        title: "Little Miss Sunshine",
        year: "(2006)",
        director: "Valerie Faris, Jonathan Dayton",
        trailer: "https://youtu.be/wvwVkllXT80",
        rated: 5,
        tagline: "A family on the verge of a breakdown",
        description: "A family loaded with quirky, colorful characters piles into an old van and road trips to California for little Olive to compete in a beauty pageant.",
        poster: "./posters/little miss sunshine (2006)/cfVDxpSgP4J7wPavgZTm8KbEai6.jpg",
    },
    {
        id: "ad-astra",
        title: "Ad Astra",
        year: "(2019)",
        director: "James Gray",
        trailer: "https://youtu.be/BsCNKuB93BA",
        rated: 3,
        tagline: "The answers we seek are just outside our reach",
        description: "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
        poster: "./posters/ad astra (2019)/ijzHDXqpPjpS92jr678hWDDlb7O.jpg",
    },
    {
        id: "10-things-i-hate-about-you",
        title: "10 Things I Hate About You",
        year: "(1999)",
        director: "Gil Junger",
        trailer: "https://youtu.be/uE7qjQlfoRs",
        rated: 5,
        tagline: "How do I loathe thee? Let me count the ways.",
        description: "On the first day at his new school, Cameron instantly falls for Bianca, the gorgeous girl of his dreams. The only problem is that Bianca is forbidden to date until her ill-tempered, completely un-dateable older sister Kat goes out, too. In an attempt to solve his problem, Cameron singles out the only guy who could possibly be a match for Kat: a mysterious bad boy with a nasty reputation of his own.",
        poster: "./posters/10 things i hate about you (1999)/kbaxSovb8mJMMHXhhkMGKST1Vfl.jpg",
    },
    {
        id: "the-batman",
        title: "The Batman",
        year: "(2022)",
        director: "Matt Reeves",
        trailer: "https://youtu.be/mqqft2x_Aa4",
        rated: 5,
        tagline: "Unmask the truth.",
        description: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        poster: "./posters/the batman (2022)/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    },
    {
        id: "parasite",
        title: "Parasite",
        year: "(2019)",
        director: "Bong Joon-ho",
        trailer: "https://youtu.be/SEUXfv87Wpk",
        rated: 5,
        tagline: "Act like you own the place.",
        description: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        poster: "./posters/parasite (2019)/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
        id: "the-menu",
        title: "The Menu",
        year: "(2022)",
        director: "Mark Mylod",
        trailer: "https://youtu.be/C_uTkUGcHv4",
        rated: 4,
        tagline: "Painstakingly prepared. Brilliantly executed.",
        description: "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
        poster: "./posters/the menu (2022)/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg",
    },
    {
        id: "the-shining",
        title: "The Shining",
        year: "(1980)",
        director: "Stanley Kubrick",
        trailer: "https://youtu.be/FZQvIJxG9Xs",
        rated: 3,
        tagline: "He came as the caretaker, but this hotel had its own guardians - who'd been there a long time",
        description: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
        poster: "./posters/the shining (1980)/nRj5511mZdTl4saWEPoj9QroTIu.jpg",
    },
    {
        id: "nomadland",
        title: "Nomadland",
        year: "(2021)",
        director: "Chloé Zhao",
        trailer: "https://youtu.be/6sxCFZ8_d84",
        rated: 2,
        tagline: "See you down the road.",
        description: "A woman in her sixties embarks on a journey through the western United States after losing everything in the Great Recession, living as a van-dwelling modern-day nomad.",
        poster: "./posters/nomadland (2021)/8Vc5EOUEIF1EUXuX9eLFf7BvN3P.jpg",
    },
    {
        id: "the-kings-speech",
        title: "The King's Speech",
        year: "(2010)",
        director: "Tom Hooper",
        trailer: "https://youtu.be/EcxBrTvLbBM",
        rated: 2,
        tagline: "Find your voice.",
        description: "The King's Speech tells the story of the man who became King George VI, the father of Queen Elizabeth II. After his brother abdicates, George ('Bertie') reluctantly assumes the throne. Plagued by a dreaded stutter and considered unfit to be king, Bertie engages the help of an unorthodox speech therapist named Lionel Logue. Through a set of unexpected techniques, and as a result of an unlikely friendship, Bertie is able to find his voice and boldly lead the country into war.",
        poster: "./posters/the kings speech (2010)/uQ538BfYLDJh3GXlzRZLo0j7PFj.jpg",
    },
    {
        id: "the-red-sea-diving-resort",
        title: "The Red Sea Diving Resort",
        year: "(2019)",
        director: "Gideon Raff",
        trailer: "https://youtu.be/80WflPMzAcw",
        rated: 1,
        tagline: "In the 1980s one partnership saved thousands of lives",
        description: "Sudan, East Africa, 1980. A team of Israeli Mossad agents plans to rescue and transfer thousands of Ethiopian Jews to Israel. To do so, and to avoid raising suspicions from the inquisitive and ruthless authorities, they establish as a cover a fake diving resort by the Red Sea.",
        poster: "./posters/the red sea diving resort (2019)/bTgd1QQFTKdxESevtffAvIvCnz2.jpg",
    },
    {
        id: "call-me-by-your-name",
        title: "Call Me by Your Name",
        year: "(2017)",
        director: "Luca Guadagnino",
        trailer: "https://youtu.be/Z9AYPxH5NTM",
        rated: 1,
        tagline: "Is it better to speak or die?",
        description: "In 1980s Italy, a relationship begins between seventeen-year-old teenage Elio and the older adult man hired as his father's research assistant.",
        poster: "./posters/call me by your name (2017)/mZ4gBdfkhP9tvLH1DO4m4HYtiyi.jpg",
    },
    {
        id: "thor-love-and-thunder",
        title: "Thor: Love and Thunder",
        year: "(2022)",
        director: "Taika Waititi",
        trailer: "https://youtu.be/Go8nTmfrQd8",
        rated: 1,
        tagline: "The one is not the only.",
        description: "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
        poster: "./posters/thor love and thunder (2022)/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    },
    {
        id: "the-emoji-movie",
        title: "The Emoji Movie",
        year: "(2017)",
        director: "Tony Leondis",
        trailer: "https://youtu.be/Rd85FEdJfTw",
        rated: 1,
        tagline: "Not easy being meh",
        description: "Gene, a multi-expressional emoji, sets out on a journey to become a normal emoji.",
        poster: "./posters/the emoji movie (2017)/7AfUVXwnfkOSWnFsPb5WdzxGNqp.jpg",
    },
    {
        id: "justice-league",
        title: "Justice League",
        year: "(2017)",
        director: "Zack Snyder",
        trailer: "https://youtu.be/3cxixDgHUYw",
        rated: 1,
        tagline: "You can't save the world alone",
        description: "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
        poster: "./posters/justice league (2017)/eRoXqOzciHkSPs1Z8pGnJMZo0Zb.jpg",
    },
    {
        id: "bird-box",
        title: "Bird Box",
        year: "(2018)",
        director: "Susanne Bier",
        trailer: "https://youtu.be/o2AsIXSh2xo",
        rated: 1,
        tagline: "Never lose sight of survival",
        description: "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
        poster: "./posters/bird box (2018)/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg",
    },
    {
        id: "a-quiet-place",
        title: "A Quiet Place",
        year: "(2018)",
        director: "John Krasinski",
        trailer: "https://youtu.be/WR7cc5t7tv8",
        rated: 2,
        tagline: "If they hear you, they hunt you.",
        description: "A family is forced to live in silence while hiding from creatures that hunt by sound.",
        poster: "./posters/a quiet place (2018)/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    },
    {
        id: "green-book",
        title: "Green Book",
        year: "(2018)",
        director: "Peter Farrelly",
        trailer: "https://youtu.be/QkZxoko_HC0",
        rated: 2,
        tagline: "Inspired by a True Friendship",
        description: "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
        poster: "./posters/green book (2018)/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
    },
    {
        id: "22-jump-street",
        title: "22 Jump Street",
        year: "(2014)",
        director: "Phil Lord, Christopher Miller",
        trailer: "https://youtu.be/qP755JkDxyM",
        rated: 2,
        tagline: "They're not 21 anymore",
        description: "After making their way through high school (twice), big changes are in store for officers Schmidt and Jenko when they go deep undercover at a local college. But when Jenko meets a kindred spirit on the football team, and Schmidt infiltrates the bohemian art major scene, they begin to question their partnership. Now they don't have to just crack the case - they have to figure out if they can have a mature relationship. If these two overgrown adolescents can grow from freshmen into real men, college might be the best thing that ever happened to them.",
        poster: "./posters/22 jump street (2014)/ajB6cGvoy04438RzvfO6Sz28yMK.jpg",
    },
    {
        id: "iron-man-2",
        title: "Iron Man 2",
        year: "(2010)",
        director: "Jon Favreau",
        trailer: "https://youtu.be/BoohRoVA9WQ",
        rated: 2,
        tagline: "It's not the armor that makes the hero, but the man inside.",
        description: "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
        poster: "./posters/iron man 2 (2010)/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
    },
    {
        id: "prey-for-the-devil",
        title: "Prey for the Devil",
        year: "(2022)",
        director: "Daniel Stamm",
        trailer: "https://youtu.be/u_jJiZ2oZgs",
        rated: 2,
        tagline: "It wants in.",
        description: "In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.",
        poster: "./posters/prey for the devil (2022)/w3s6XEDNVGq5LUlghqs6VlvsvL6.jpg",
    },
    {
        id: "inside-out",
        title: "Inside Out",
        year: "(2015)",
        director: "Pete Docter",
        trailer: "https://youtu.be/yRUAzGQ3nSY",
        rated: 2,
        tagline: "Meet the little voices inside your head.",
        description: "Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Riley's guiding emotions— Joy, Fear, Anger, Disgust and Sadness—live in Headquarters, the control centre inside Riley's mind, where they help advise her through everyday life and tries to keep things positive, but the emotions conflict on how best to navigate a new city, house and school.",
        poster: "./posters/inside out (2015)/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    },
    {
        id: "thor",
        title: "Thor",
        year: "(2011)",
        director: "Kenneth Branagh",
        trailer: "https://youtu.be/JOddp-nlNvQ",
        rated: 2,
        tagline: "Two worlds. One hero.",
        description: "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
        poster: "./posters/thor (2011)/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
    },
    {
        id: "suicide-squad",
        title: "Suicide Squad",
        year: "(2016)",
        director: "David Ayer",
        trailer: "https://youtu.be/CmRih_VtVAs",
        rated: 2,
        tagline: "Worst Heroes Ever",
        description: "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences.",
        poster: "./posters/suicide squad (2016)/xFw9RXKZDvevAGocgBK0zteto4U.jpg",
    },
    {
        id: "xmen-days-of-future-past",
        title: "X-Men: Days of Future Past",
        year: "(2014)",
        director: "Bryan Singer",
        trailer: "https://youtu.be/pK2zYHWDZKo",
        rated: 3,
        tagline: "To save the future, they must alter the past.",
        description: "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.",
        poster: "./posters/xmen days of future past (2014)/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
    },
    {
        id: "see-how-they-run",
        title: "See How They Run",
        year: "(2022)",
        director: "Tom George",
        trailer: "https://youtu.be/Q00qh7Ab6Mk",
        rated: 3,
        tagline: "The greatest murder ever staged.",
        description: "In the West End of 1950s London, plans for a movie version of a smash-hit play come to an abrupt halt after a pivotal member of the crew is murdered. When world-weary Inspector Stoppard and eager rookie Constable Stalker take on the case, the two find themselves thrown into a puzzling whodunit within the glamorously sordid theater underground, investigating the mysterious homicide at their own peril.",
        poster: "./posters/see how they run (2022)/r3rpSAi2yukZwr9H2km0WKGODWo.jpg",
    },
    {
        id: "love-and-other-drugs",
        title: "Love & Other Drugs",
        year: "(2010)",
        director: "Edward Zwick",
        trailer: "https://youtu.be/h6w7Dh-QxzY",
        rated: 3,
        tagline: "Addicted to one-night stands or dependent on one another?",
        description: "Maggie is an alluring free spirit who won't let anyone – or anything – tie her down. But she meets her match in Jamie, whose relentless and nearly infallible charm serves him well with the ladies and the cutthroat world of pharmaceutical sales. Maggie and Jamie's evolving relationship takes them both by surprise, as they find themselves under the influence of the ultimate drug: love.",
        poster: "./posters/love and other drugs (2010)/1nXN4e3IoTJD42ci7WHZeI1Cgpm.jpg",
    },
    {
        id: "neon-genesis-evangelion",
        title: "Neon Genesis Evangelion",
        year: "(1995)",
        director: "Hideaki Anno",
        trailer: "https://youtu.be/13nSISwxrY4",
        rated: 5,
        description: "At the turn of the century, the Angels returned to Earth, seeking to wipe out humanity in an apocalyptic fury. Devastated, mankind's last remnants moved underground to wait for the day when the Angels would come back to finish the job. Fifteen years later, that day has come... but this time, humanity is ready to fight back with terrifying bio-mechanical weapons known as the Evangelions. Watch as Shinji, Rei, Asuka and the rest of the mysterious shadow agency Nerv battle to save earth from total annihilation.",
        poster: "./posters/neon genesis evangelion (1995)/y2ah9t0navXyIvoHg1uIbIHO3tt.jpg",
    },
    {
        id: "memento",
        title: "Memento",
        year: "(2000)",
        director: "Christopher Nolan",
        trailer: "https://youtu.be/4CV41hoyS8A",
        rated: 4,
        tagline: "Some memories are best forgotten.",
        description: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
        poster: "./posters/memento (2000)/bDgEwnPFcPrJcM5xvkt8EphZ9A3.jpg",
    },
    {
        id: "clueless",
        title: "Clueless",
        year: "(1995)",
        director: "Amy Heckerling",
        trailer: "https://youtu.be/Mgjwq1ZzdPQ",
        rated: 4,
        tagline: "Sex. Clothes. Popularity. Is there a problem here?",
        description: "Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school's pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other. Emboldened by her success, she decides to give hopelessly klutzy new student Tai a makeover. When Tai becomes more popular than she is, Cher realizes that her disapproving ex-stepbrother was right about how misguided she was -- and falls for him.",
        poster: "./posters/clueless (1995)/8AwVTcgpTnmeOs4TdTWqcFDXEsA.jpg",
    },
    {
        id: "the-devil-wears-prada",
        title: "The Prada Wears Prada",
        year: "(2006)",
        director: "David Frankel",
        trailer: "https://youtu.be/6ZOZwUQKu3E",
        rated: 4,
        tagline: "Meet Andy Sachs. A million girls would kill to have her job. She's not one of them.",
        description: "Andy moves to New York to work in the fashion industry. Her boss is extremely demanding, cruel and won't let her succeed if she doesn't fit into the high class elegant look of their magazine.",
        poster: "./posters/the devil wears prada (2006)/vJDNtAsMsQNfy8uG6jy9HnlVXYo.jpg",
    },
    {
        id: "gifted",
        title: "Gifted",
        year: "(2017)",
        director: "Marc Webb",
        trailer: "https://youtu.be/x7CAjpdRaXU",
        rated: 4,
        description: "Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.",
        poster: "./posters/gifted (2017)/7YB2YrMwIm1g8FyZtlvmVDfRnAT.jpg",
    },
    {
        id: "the-imitation-game",
        title: "The Imitation Game",
        year: "(2014)",
        director: "Morten Tyldum",
        trailer: "https://youtu.be/j2jRs4EAvWM",
        rated: 4,
        tagline: "The true enigma was the man who cracked the code.",
        description: "Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.",
        poster: "./posters/the imitation game (2014)/lLZxUpNnLHklJ7IA75CbjfE0xra.jpg",
    },
    {
        id: "gone-girl",
        title: "Gone Girl",
        year: "(2014)",
        director: "David Fincher",
        trailer: "https://youtu.be/JU9PdgB3rsk",
        rated: 4,
        tagline: "You don't know what you've got 'til it's...",
        description: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
        poster: "./posters/gone girl (2014)/l3TzM0e6OqbaWHLJrJ594KNjhL0.jpg",
    },
    {
        id: "big-hero-6",
        title: "Big Hero 6",
        year: "(2014)",
        director: "Don Hall",
        trailer: "https://youtu.be/z3biFxZIJOQ",
        rated: 4,
        tagline: "From the creators of Wreck-It Ralph and Frozen.",
        description: "A special bond develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.",
        poster: "./posters/big hero 6 (2014)/7JEqFZ47vD5Bii3gSZc99uPaX18.jpg",
    },
    {
        id: "smile",
        title: "Smile",
        year: "(2022)",
        director: "Parker Finn",
        trailer: "https://youtu.be/BcDK7lkzzsU",
        rated: 3,
        tagline: "Once you see it, it’s too late.",
        description: "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
        poster: "./posters/smile (2022)/67Myda9zANAnlS54rRjQF4dHNNG.jpg",
    },
    {
        id: "megamind",
        title: "Megamind",
        year: "(2010)",
        director: "Tom McGrath",
        trailer: "https://youtu.be/ead9HCX9fe4",
        rated: 3,
        tagline: "His brain is off the chain.",
        description: "Bumbling supervillain Megamind finally defeats his nemesis, the superhero Metro Man. But without a hero, he loses all purpose and must find new meaning to his life.",
        poster: "./posters/megamind (2010)/7rb7ksmpmBALC9P154wtf0ot2ee.jpg",
    },
    {
        id: "13-going-on-30",
        title: "13 Going on 30",
        year: "(2004)",
        director: "Gary Winick",
        trailer: "https://youtu.be/5UrCaXLBN30",
        rated: 3,
        tagline: "For some, 13 feels like it was just yesterday. For Jenna, it was.",
        description: "After total humiliation at her thirteenth birthday party, Jenna Rink wants to just hide until she's thirty. With a little magic, her wish is granted, but it turns out that being thirty isn't as always as awesome as she thought it would be!",
        poster: "./posters/13 going on 30 (2004)/l8d8CGdAGAwLvDXW5lSQ7churfI.jpg",
    },
    {
        id: "the-perks-of-being-a-wallflower",
        title: "The Perks of Being a Wallflower",
        year: "(2012)",
        director: "Stephen Chbosky",
        trailer: "https://youtu.be/n5rh7O4IDc0",
        rated: 3,
        tagline: "We are infinite.",
        description: "Pittsburgh, Pennsylvania, 1991. High school freshman Charlie is a wallflower, always watching life from the sidelines, until two senior students, Sam and her stepbrother Patrick, become his mentors, helping him discover the joys of friendship, music and love.",
        poster: "./posters/the perks of being a wallflower (2012)/trx7UZ6kKoR24MYZwOMqJKki0G1.jpg",
    },
    {
        id: "spider-man-no-way-home",
        title: "Spider-Man: No Way Home",
        year: "(2021)",
        director: "Jon Watts",
        trailer: "https://youtu.be/JfVOs4VSpmA",
        rated: 3,
        tagline: "The Multiverse unleashed.",
        description: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        poster: "./posters/spider man no way home (2021)/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    },
    {
        id: "avengers-endgame",
        title: "Avengers: Endgame",
        year: "(2019)",
        director: "Joe Russo, Anthony Russo",
        trailer: "https://youtu.be/hA6hldpSTF8",
        rated: 3,
        tagline: "Avenge the fallen.",
        description: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        poster: "./posters/avengers endgame (2019)/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    },
    {
        id: "the-anthem-of-the-heart",
        title: "The Anthem of the Heart",
        year: "(2015)",
        director: "Tatsuyuki Nagai",
        trailer: "https://youtu.be/EnbgMjdguxI",
        rated: 3,
        tagline: "Beautiful Word, Beautiful World.",
        description: "A young girl had her voice magically taken away so that she would never hurt people with it, but her outlook changes when she encounters music and friendship. Will Naruse be able to convey the anthem of her heart?",
        poster: "./posters/the anthem of the heart (2015)/h9UUOcgaHClUIQqebo6hBDMOE89.jpg",
    },
    {
        id: "deadpool",
        title: "Deadpool",
        year: "(2016)",
        director: "Tim Miller",
        trailer: "https://youtu.be/FyKWUTwSYAs",
        rated: 3,
        tagline: "Witness the beginning of a happy ending.",
        description: "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
        poster: "./posters/deadpool (2016)/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
    },
    {
        id: "kung-fu-panda",
        title: "Kung Fu Panda",
        year: "(2008)",
        director: "Mark Osborne, John Stevenson",
        trailer: "https://youtu.be/PXi3Mv6KMzY",
        rated: 5,
        tagline: "Prepare for awesomeness.",
        description: 'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.',
        poster: "./posters/kung fu panda (2008)/mKMupnD5ilFRPXnyKTE6JEzEm73.jpg",
    },
    {
        id: "my-neighbour-totoro",
        title: "My Neighbour Totoro",
        year: "(1988)",
        director: "Hayao Miyazaki",
        trailer: "https://youtu.be/srW-wajSxog",
        rated: 5,
        description: "Two sisters move to the country with their father in order to be closer to their hospitalized mother, and discover the surrounding trees are inhabited by Totoros, magical spirits of the forest. When the youngest runs away from home, the older sister seeks help from the spirits to find her.",
        poster: "./posters/my neighbour totoro (1988)/fdQTEzDt3CSAlJU8x2DwutfesDG.jpg",
    },
    {
        id: "the-banshees-of-inisherin",
        title: "The Banshees of Inisherin",
        year: "(2022)",
        director: "Martin McDonagh",
        trailer: "https://youtu.be/uRu3zLOJN2c",
        rated: 5,
        tagline: "Everything was fine yesterday.",
        description: "Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.",
        poster: "./posters/the banshees of inisherin (2022)/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
    },
    {
        id: "",
        title: "",
        year: "",
        director: "",
        trailer: "",
        rated: "",
        tagline: "",
        description: "",
        poster: "",
    },


];