window.movies = [
    {
        id: "aftersun",
        name: "Aftersun",
        year: "(2022)",  
        director: "Charlotte Wells",
        trailer: "https://youtu.be/vXKcWRu8K_U",
        rated: "5",
        description: "Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between miniDV footage as she tries to reconcile the father she knew with the man she didn't.",
    },
    {
        id: "everything-everywhere-all-at-once",
        name: "Everything Everywhere All At Once",
        year: "(2022)",
        director: "Daniel Kwan, Daniel Scheinert",
        trailer: "https://youtu.be/wxN1T1uxQ2g",
        rated: "5",
        description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    },
    {
        id: "heat",
        name: "Heat",
        year: "(1995)",
        director: "Michael Mann",
        trailer: "https://youtu.be/14oNcFxiVaQ",
        rated: "5",
        description: "Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
    },
    {
        id: "minari",
        name: "Minari",
        year: "(2020)",
        director: "Lee Isaac Chung",
        trailer: "https://youtu.be/KQ0gFidlro8",
        rated: "5",
        description: "A Korean American family moves to an Arkansas farm in search of its own American dream. Amidst the challenges of this new life in the strange and rugged Ozarks, they discover the undeniable resilience of family and what really makes a home.",
    },
    {
        id: "chunking-express",
        name: "Chunking Express",
        year: "(1994)",
        director: "Wong Kar-wai",
        trailer: "https://youtu.be/C3NDz_7KP2g",
        rated: "5",
        description: "Two melancholic Hong Kong policemen fall in love: one with a mysterious underworld figure, the other with a beautiful and ethereal server at a late-night restaurant.",
    },
    {
        id: "nope",
        name: "Nope",
        year: "2022",
        director: "Jordan Peele",
        trailer: "https://youtu.be/In8fuzj3gck",
        rated: "5",
        description: "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
    }

]