window.movies = [
    {
        id: "aftersun",
        title: "Aftersun",
        year: "(2022)",  
        director: "Charlotte Wells",
        trailer: "https://youtu.be/vXKcWRu8K_U",
        rated: 5,
        description: "Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between miniDV footage as she tries to reconcile the father she knew with the man she didn't.",
        poster: "./posters/aftersun (2022)/eggpklKcxDFHBYd3tTjO258op4R.jpg",
    },
    {
        id: "everything-everywhere-all-at-once",
        title: "Everything Everywhere All At Once",
        year: "(2022)",
        director: "Daniel Kwan, Daniel Scheinert",
        trailer: "https://youtu.be/wxN1T1uxQ2g",
        rated: 5,
        description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
        poster: "./posters/everything everywhere all at once (2022)/q2VDgaPHJVZ6YXyXdycVM2F2d7E.jpg",
    },
    {
        id: "heat",
        title: "Heat",
        year: "(1995)",
        director: "Michael Mann",
        trailer: "https://youtu.be/14oNcFxiVaQ",
        rated: 5,
        description: "Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
        poster: "./posters/heat (1995)/twXYxcrup1QzyT84g2kbuz1iN01.jpg",
    },
    {
        id: "minari",
        title: "Minari",
        year: "(2020)",
        director: "Lee Isaac Chung",
        trailer: "https://youtu.be/KQ0gFidlro8",
        rated: 5,
        description: "A Korean American family moves to an Arkansas farm in search of its own American dream. Amidst the challenges of this new life in the strange and rugged Ozarks, they discover the undeniable resilience of family and what really makes a home.",
        poster: "./posters/minari (2021)/6mPNdmjdbVKPITv3LLCmQoKs9Zw.jpg",
    },
    {
        id: "chunking-express",
        title: "Chunking Express",
        year: "(1994)",
        director: "Wong Kar-wai",
        trailer: "https://youtu.be/C3NDz_7KP2g",
        rated: 5,
        description: "Two melancholic Hong Kong policemen fall in love: one with a mysterious underworld figure, the other with a beautiful and ethereal server at a late-night restaurant.",
        poster: "./posters/chunking express (1994)/8Zzg6ph0WWXyfnYTmduen6FQXtY.jpg",
    },
    {
        id: "nope",
        title: "Nope",
        year: "(2022)",
        director: "Jordan Peele",
        trailer: "https://youtu.be/In8fuzj3gck",
        rated: 5,
        description: "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
        poster: "./posters/nope (2022)/krvPgQ44o33hEpZfXnPTDoZz62S.jpg",
    },
    {
        id: "house-of-hummingbird",
        title: "House of Hummingbird",
        year: "(2019)",
        director: "Kim Bora",
        trailer: "https://youtu.be/P1OwDXmdedQ",
        rated: 5,
        description: "Whatever she does, Eunhee feels like an outsider. Then her new Chinese teacher turns out to be so utterly different from everybody else. A compassionate and meticulously told narrative of a seemingly regular summer that leaves nothing unchanged.",
        poster: "./posters/house of hummingbird (2019)/azqkMjfwdXuK6OzrrGNYyUnHOAQ.jpg",
    },
    {
        id: "in-the-mood-for-love",
        title: "In the Mood for Love",
        year: "(2000)",
        director: "Wong Kar-wai",
        trailer: "https://youtu.be/m8GuedsQnWQ",
        rated: 5,
        description: "Taking place in Hong Kong of 1962, a melancholy story about the love between a woman and a man who live in the same building and one day find out that their husband and wife had an affair with each other.",
        poster: "./posters/in the mood for love (2000)/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg",
    },
    {
        id: "spirited-away",
        title: "Spirited Away",
        year: "(2001)",
        director: "Hayao Miyazaki",
        trailer: "https://youtu.be/ByXuk9QqQkk",
        rated: 5,
        description: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        poster: "./posters/spirited away (2001)/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    },
    {
        id: "all-about-lily-chou-chou",
        title: "All About Lily Chou-Chou",
        year: "(2001)",
        director: "Shunji Iwai",
        trailer: "https://youtu.be/Kwlh-z2R8QE",
        rated: 5,
        description: "Charts the troubled teenage years of students Yūichi Hasumi and Shūsuke Hoshino, exploring the shifting and complex power dynamics of their relationship against the backdrop of Yūichi's love for the dreamy and abstract music of fictional pop star Lily Chou-Chou.",
        poster: "./posters/all about lily chou-chou (2001)/cgYcTxXDAYJg8Wc6a15xe2SUZPH.jpg",
    },
    {
        id: "the-shawshank-redemption",
        title: "The Shawshank Redemption",
        year: "(1994)",
        director: "Frank Darabont",
        trailer: "https://youtu.be/PLl99DlL6b4",
        rated: 4,
        description: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        poster: "./posters/the shawshank redemption (1994)/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
    },
    {
        id: "pearl",
        title: "Pearl",
        year: "(2022)",
        director: "Ti West",
        trailer: "https://youtu.be/L5PW5r3pEOg",
        rated: 4,
        description: "Trapped on her family’s isolated farm, Pearl must tend to her ailing father under the bitter and overbearing watch of her devout mother. Lusting for a glamorous life like she’s seen in the movies, Pearl’s ambitions, temptations, and repressions collide.",
        poster: "./posters/pearl (2022)/z3NsdQn6rEWxY8JI9stsuwkAyk2.jpg",
    },
    {
        id: "bones-and-all",
        title: "Bones and All",
        year: "(2022)",
        director: "Luca Guadagnino",
        trailer: "https://youtu.be/pjMt1MIk2EA",
        rated: 4,
        description: "Abandoned by her father, a young woman embarks on a thousand-mile odyssey through the backroads of America where she meets a disenfranchised drifter. But despite their best efforts, all roads lead back to their terrifying pasts and to a final stand that will determine whether their love can survive their otherness.",
        poster: "./posters/bones and all (2022)/oVQYItnGtRWkbCpQRD4ISXTZPP8.jpg",
    },
    {
        id: "tar",
        title: "TÁR",
        year: "(2022)",
        director: "Todd Field",
        trailer: "https://youtu.be/Na6gA1RehsU",
        rated: 3,
        description: "The film, set in the international world of classical music, centers on Lydia Tár, widely considered one of the greatest living composer/conductors and first-ever female chief conductor of a major German orchestra.",
        poster: "./posters/tar (2022)/cmXcIwFMk4AlSaCtcnubSjkRl6q.jpg",
    },
    {
        id: "",
        title: "",
        year: "",
        director: "",
        trailer: "",
        rated: "",
        description: "",
        poster: "",
    }


];